outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

baseURL: "https://blog.bahrani.my.id/"
languageCode: id-id
title: Bahrani Blog
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

params:
  title: Bahrani Blog
  description: "Blog pribadi tentang Networking, Automation, dan Teknologi"
  keywords: [Blog, Portfolio, PaperMod, Networking, Automation]
  author: Bahrani
  # author: ["Me", "You"] # multiple authors
  images: ["/img/bahrani.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/bahrani.jpg"
    favicon16x16: "/img/bahrani.jpg"
    favicon32x32: "/img/bahrani.jpg"
    apple_touch_icon: "/img/bahrani.jpg"
    safari_pinned_tab: "/img/bahrani.jpg"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true
    title: "Hi, Saya Bahrani 👋"
    subtitle: "🔧 Network Engineer · 🤖 Automation Enthusiast · 📚 Lifelong Learner\n\nTempat saya mencatat dan berbagi hal-hal yang saya pelajari tentang **Networking**, **Network Automation**, dan **Teknologi**."
    imageUrl: "/img/bahrani.jpg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Bahrani
    buttons:
      - name: 📝 Blog
        url: /docs/
 #     - name: 📝 Blog
 #       url: "https://bahrani.my.id"
      - name: 🏷️ Tags
        url: /tags/
      - name: 🔍 Search
        url: /search/

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/bahran_07/"
    - name: github
      url: "https://github.com/bahrani667/"
    - name: linkedin
      url: "https://www.linkedin.com/in/bahranibahrani/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/bahranibahrani/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/ # Update the URL as per your site structure
      weight: 30 # Adjust weight to determine its position in the menu

pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
